syntax on           " turn on syntax highlighting
set number          " turn on line numbers
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces
set lazyredraw      " redraw only when we need to.
set showmatch       " highlight matching [{()}]

" set cursorline      " highlight current line
" set incsearh        " search as characters are entered
" set hlsearch        " hilights while searching
" set wildmenu        " visual autocomplete for command menu
